name: "Deploy to server"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Stop Update Run"
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          FIRSTSSH: "Stop container"
          LASTSSH: "Start updated container"
          WORKDIR: ${{ secrets.SERVER_WORKDIR }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          connect_timeout: 10s

          first_ssh: |
            echo $WELCOME &&
            cd $WORKDIR &&
            docker compose down 
          scp: |
            . => $WORKDIR
          last_ssh: |
            echo $LASTSSH && 
            docker compose build &&
            docker compose up
