name: "Deploy to server"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Stop running container"
        uses: appleboy/ssh-action@v1
        continue-on-error: true
        env:
          SERVER_WORKDIR: ${{ env.SERVER_WORKDIR }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd $SERVER_WORKDIR && ls -a && docker compose down
            
      - name: "Copy repository to server"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: ${{ env.SERVER_WORKDIR }}

      - name: "Build and start container"
        uses: appleboy/ssh-action@v1
        env:
          SERVER_WORKDIR: ${{ env.SERVER_WORKDIR }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ACTIONS_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd $SERVER_WORKDIR && ls -a && docker compose build && docker compose up -d
